### ISSUE TITLE
Integrate horde as a web client

### ISSUE THREAD

**Issue by anuudb** [LankaSoftwareFoundation/copper-base#30]

**Comment by tharindu99** [comment]
Hord is a webmail tool with multiple additional functionalities like notes/task management / calendar ..etc. But it will use separate relational db and that may have to maintain with and additional weight (regarding the backup and recovery). However if we can integrate horde as much as similar to rainloop integration, it make a lot of advantages for this solution.

**Comment by anuudb** [comment]
Completed in initial level.
